version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: adl
      MONGO_INITDB_ROOT_PASSWORD: adl123
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - docker-network  

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: adl
      KEYCLOAK_PASSWORD: adl123
      DB_VENDOR: POSTGRES  # You can change this to other databases like MySQL, H2, etc.
      DB_ADDR: postgres  # If using a different database, provide its hostname here
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: adl123
      #KEYCLOAK_IMPORT: /tmp/realm-export.json  # Optional: Import your realm configuration
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - docker-network    

  postgres:  # Add the PostgreSQL container for Keycloak
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: adl123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker-network  
volumes:
  mongo_data:
  keycloak_data:
  postgres_data:

networks:
  docker-network:
    driver: bridge
